name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.FLICKR_API_KEY }}
      run: |
        chmod +x ./.github/workflows/setup_env.sh
        ./.github/workflows/setup_env.sh "$SUPER_SECRET"

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive build output
      uses: actions/upload-artifact@v3
      with:
        name: build_output
        path: ./app/build/outputs
        retention-days: 1

    - name: Archive build reports
      uses: actions/upload-artifact@v3
      with:
        name: build_output
        path: ./app/build/reports
        retention-days: 1
